ccr_path = "config/ccr.toml"
dragon_path = "C:/Program Files (x86)/Nuance/NaturallySpeaking15/Program/natspeak.exe"
editor_path = "C:/Program Files/Windows NT/Accessories/wordpad.exe"
# editor_path = "C:/Program Files/Sublime Text 3/sublime_text.exe"
ccr_modules = ["core",
				"ScientificNotebook55",
				"LyX",
				"latex",
				"latex_maths",
				"alias"
				]
app_modules = ["sublime",
				"sumatrapdf",
                "wordpad"
				]
max_ccr_repetitions = 16
alternative_letters = false
alternative_directions = false
use_aenea = false
# Words to be removed from the dragon vocabulary
delete_words = ["one-to-one"]
# Words to be added to the dragon vocabulary
add_words = [
    "heteroscedasticity",
    "homoscedasticity",
    "leptokurtosis"
    ]